# Generated by Django 5.0.6 on 2024-08-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahalle',
            name='semt',
        ),
        migrations.AddField(
            model_name='mahalle',
            name='ilce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalleler', to='turkiye.ilce'),
        ),
        migrations.DeleteModel(
            name='Semt',
        ),
    ]
