# Generated by Django 5.0.6 on 2024-08-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0002_remove_mahalle_semt_mahalle_ilce_delete_semt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahalle',
            name='ilce',
        ),
        migrations.CreateModel(
            name='Semt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semtler', to='turkiye.ilce')),
            ],
        ),
        migrations.AddField(
            model_name='mahalle',
            name='semt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalleler', to='turkiye.semt'),
        ),
    ]
