# Generated by Django 5.0.6 on 2024-08-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0003_remove_mahalle_ilce_semt_mahalle_semt'),
    ]

    operations = [
        migrations.AddField(
            model_name='semt',
            name='il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semt_il', to='turkiye.il'),
        ),
    ]
