# Generated by Django 5.0.6 on 2024-08-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0004_semt_il'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalle',
            name='il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalle_il', to='turkiye.il'),
        ),
        migrations.AddField(
            model_name='mahalle',
            name='ilce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahallle_ilce', to='turkiye.ilce'),
        ),
        migrations.AlterField(
            model_name='mahalle',
            name='semt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalle_semt', to='turkiye.semt'),
        ),
    ]
