# Generated by Django 5.0.6 on 2024-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0005_mahalle_il_mahalle_ilce_alter_mahalle_semt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalle',
            name='posta_kodu',
            field=models.IntegerField(default=0),
        ),
    ]
