# Generated by Django 5.0.6 on 2024-08-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0006_mahalle_posta_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalle',
            name='ilce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalle_ilce', to='turkiye.ilce'),
        ),
        migrations.AlterField(
            model_name='semt',
            name='ilce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semt_ilce', to='turkiye.ilce'),
        ),
    ]
