# Generated by Django 5.0.6 on 2024-08-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkiye', '0007_alter_mahalle_ilce_alter_semt_ilce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilce',
            name='il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turkiye.il'),
        ),
    ]
