# Generated by Django 5.0.6 on 2024-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sahis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True)),
                ('adres', models.CharField(max_length=255)),
                ('isim', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('koy', models.CharField(max_length=50)),
                ('ada', models.CharField(max_length=50)),
                ('parsel', models.CharField(max_length=50)),
                ('koordinat1', models.CharField(max_length=50)),
                ('koordinat2', models.CharField(max_length=50)),
            ],
        ),
    ]
