# Generated by Django 5.0.6 on 2024-07-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sahis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True)),
                ('adres', models.CharField(max_length=255)),
                ('isim', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('koy', models.CharField(max_length=50)),
                ('ada', models.CharField(max_length=50)),
                ('parsel', models.CharField(max_length=50)),
                ('koordinat1', models.CharField(max_length=50)),
                ('koordinat2', models.CharField(max_length=50)),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma.firma')),
            ],
        ),
    ]
