# Generated by Django 5.0.6 on 2024-07-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_remove_firma_sahislar'),
        ('sahis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahis',
            name='firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firma.firma'),
        ),
    ]
