# Generated by Django 5.0.6 on 2024-07-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_remove_firma_sahislar'),
        ('sahis', '0002_sahis_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahis',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma.firma'),
        ),
    ]
