# Generated by Django 5.0.6 on 2024-08-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahis', '0002_sahis_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sahis',
            name='info',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sahis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
