# Generated by Django 5.0.6 on 2024-08-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahis', '0003_sahis_info_alter_sahis_user'),
        ('turkiye', '0006_mahalle_posta_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahis',
            name='basvuru_mahalle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turkiye.mahalle'),
        ),
    ]
