# Generated by Django 5.0.6 on 2024-08-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahis', '0004_sahis_basvuru_mahalle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahis',
            name='il',
        ),
        migrations.RemoveField(
            model_name='sahis',
            name='ilce',
        ),
        migrations.RemoveField(
            model_name='sahis',
            name='koy',
        ),
    ]
