# Generated by Django 5.0.6 on 2024-08-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahis', '0005_remove_sahis_il_remove_sahis_ilce_remove_sahis_koy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sahis',
            old_name='basvuru_mahalle_id',
            new_name='mahalle',
        ),
    ]
