# Generated by Django 5.0.6 on 2024-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells_map', '0003_alter_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
