# Generated by Django 5.0.6 on 2024-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sahis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('meslek', models.CharField(max_length=100)),
                ('diploma_oda_sicil_no', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=255)),
                ('sahislar', models.ManyToManyField(related_name='firmalar', to='sahis.sahis')),
            ],
        ),
    ]
