# Generated by Django 5.0.6 on 2024-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
        ('sahis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='sahislar',
            field=models.ManyToManyField(null=True, related_name='firmalar', to='sahis.sahis'),
        ),
    ]
