# Generated by Django 5.0.6 on 2024-07-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_alter_firma_sahislar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='sahislar',
        ),
    ]
